/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Azat Ismagilov
 */

                                         /*..         ....
                                    ..',,'..............''...'''.','..
                                  .';'..                          ..',,'.
                                 .'..                                 .';,.
                                .'.              .:ol;.                 .';.
                                ..              .cO00k:.                  .,.
                               ..          .'...;k00Od'                   .'.
                              ...        .;xOkxdk00Od,                    ...
                             ...        .,x0000000Od;.                     ..
                             .'         .cO00OOOOOOd;'...                 ...
                            .'.          .;lxkOOOO00Okkxo:.               .'.
                           .'.             .cxOOOOO000000Ol.              .'.
                          .'.             .ck00OOd::oxOOOOl.              .,.
                          ''...,;''''''''':kKK0Od,. ..:xOo'               .,.
                         ';,;;;:,..........;lxOx:.    .';'               .''
                        'cc;..               .,;:,..                     ...
                       ,oc.       ..........    .',:;,..                 ...
                      'o:.     .,;;;,,,,;;;;;'.    ..,;;,..              ...
                      ';.      ...         .,::.       .,::'.            .'.
                      ..                     .',.        ..;;'.         ...
                     ..          .',,;;,'.                  ':;'.       .,.
                    .,::;,.        .......                   .';:'.    .,,.
                    .;dOK0x;.                         .        .':;.   .,.
                    ...,cdxdl;.              ..,;;;cloddoc;.     .,:,. .,.
                   .     ...;cl:.          ':ldxxdocccclol;.      ..:;.',.
                   .   .;llc;',c;.       .,:,''';::;'.  ..          .;:;'
                      .:xdoxko,',.      .,:. .;llc:ldl.              .;c.
                      .lxdoxkd:''.     .;:.  .cxl'';od;.          .. .,,
                      .:clool;.',.     .:'   .:dxolccl;.         .::;,:'
                       .;::,.. .,.     .;.   .,:;:;,,;'         .,;,:ol.
                         ..    ',.     .;.    .',,,,,.          .,:llc;.
                              .,'      .,.                      .;lxxc'
                             .,;.      .;.                      .;lxxc.
            ..              .;;.       .:'                      .;cc,.
           ...';'          .;;.        .;:.                      ,:'
          .;c:;.       .. .,;.       ....,;.                     .'.
         .,lc,.      .':,..,:,''....;c:;'':'..              ..   .'.
         .;:;.      .,:'   .::,,;;;;;..',;,..,,.            .,.  .'.
        .'',,.     .,;.                      .;,            .'.  ...
        .'',,.    .,;.                        ';.           .,.  .'.
        .'...     .;.                         .,,.          .,'   ..
        .'.      .;,.                          .::.         .,'   .
        .'.     .,;.                            ,c'         .,'  .'.
        .'.     .:'                             .,'          .. .,'
         ''.    ,;.    .....................    .;'            .:,
         .,.   .,;.   ..'''''''''''''''''','.  .,;.           .::.
          .,.   ,;.                           .,;.           .;,.
          .,,.  .:,.                         .;;.          .''.
           .,'   .'.                         ...          .,.
            .''                                          .,.
             .,'.                                       .'.
              .'.                                      .*/

#include <fstream>

#include <iostream>
#include <algorithm>
#include <vector>
#include <queue>
#include <numeric>
#include <set>
#include <map>

#define int long long
#define ld long double
#define fs first
#define sc second
#define pb push_back
#define ppb pop_back
#define pf push_front
#define ppf pop_front
#define eb emplace_back
#define mp make_pair
#define len(v) ((int)v.size())
#define vc vector
#define pr pair
#define all(v) v.begin(), v.end()
//#pragma GCC optimize("Ofast")
//#pragma GCC target("sse,sse2,sse3,ssse3,sse4,popcnt,abm,mmx,tune=native")
//#pragma GCC optimize("unroll-loops")

using namespace std;

template<typename T, typename U>
inline ostream &operator<<(ostream &_out, const pair<T, U> &_p) {
    _out << _p.first << ' ' << _p.second;
    return _out;
}

template<typename T, typename U>
inline istream &operator>>(istream &_in, pair<T, U> &_p) {
    _in >> _p.first >> _p.second;
    return _in;
}

template<typename T>
inline ostream &operator<<(ostream &_out, const vector<T> &_v) {
    if (_v.empty()) { return _out; }
    _out << _v.front();
    for (auto _it = ++_v.begin(); _it != _v.end(); ++_it) { _out << ' ' << *_it; }
    return _out;
}

template<typename T>
inline istream &operator>>(istream &_in, vector<T> &_v) {
    for (auto &_i : _v) { _in >> _i; }
    return _in;
}

const int MAXN = 3e5;
const int INF = 1e9;
const int MOD = 1e9 + 7;

string to_low(string s) {
    for (auto &v : s) {
        if ('A' <= v && v <= 'Z') {
            v = (v - 'A' + 'a');
        }
    }
    return s;
}

class spcheck {
public:
    void solve(std::istream &in, std::ostream &out) {
        int n;
        string a, b;
        in >> n >> a >> b;
        string s;
        vector<string> words, to_delete;
        map<string, int> earliest;
        for (int i = 0; i < n; i++) {
            in >> s;
            to_delete.pb(s);
        }
        while (in >> s) {
            string word = "";
            for (auto v : s) {
                if (v == '_' || ('0' <= v && v <= '9') || ('a' <= v && v <= 'z') || ('A' <= v && v <= 'Z')) {
                    word.pb(v);
                } else {
                    if (len(word) > 0) {
                        words.pb(word);
                    }
                    word = "";
                }
            }
            if (len(word) > 0) {
                words.pb(word);
            }
        }
        map<string, int> tosort;
        int counter = 1;
        for (auto word : words) {
            if (len(word) == 0) {
                exit(1);
            }
            bool is_normal = 0;
            auto wordb = to_low(word);
            for (auto v : wordb) {
                if (('a' <= v && v <= 'z') || v == '_') {
                    is_normal = 1;
                    break;
                }
            }
            if (b == "no" && '0' <= word[0] && word[0] <= '9') {
                is_normal = 0;
            }
            if (is_normal) {
                if (a == "yes") {
                    if (tosort[word] == 0) {
                        earliest[word] = counter++;
                    }
                    tosort[word]++;
                } else {
                    if (tosort[wordb] == 0) {
                        earliest[wordb] = counter++;
                    }
                    tosort[wordb]++;
                }
            }
        }
        for (auto word : to_delete) {
            string wordb = to_low(word);
            if (a == "yes") {
                tosort[word] = 0;
            } else {
                tosort[wordb] = 0;
            }
        }
        pr<pr<int, int>, string> ans = {{0, 0}, ""};
        for (auto v : tosort) {
            ans = max(ans, {{v.sc, -earliest[v.fs]}, v.fs});
        }
        if (ans.fs.fs == 0) {
            exit(1);
        }
        out << ans.sc;
    }
};


signed main() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
	spcheck solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
